---
version: 2.1

executors:

  remote-terminal:
    docker:
      - image: quay.io/feedyard/remote-terminal
    
jobs:
  build:
    executor: remote-terminal
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: greet
          command: echo 'remote-terminal running...'
 